[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
authors = [{ name = "Yury Gorishniy" }]
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = ["torch >=1.8,<3"]
dynamic = ["version", "description"]
keywords = [
    "artificial intelligence",
    "deep learning",
    "library",
    "python",
    "pytorch",
    "research",
    "torch",
    "tabular",
    "tabular data",
]
license = { file = "LICENSE" }
name = "rtdl_revisiting_models"
requires-python = ">=3.8"

[project.urls]
Code = "https://github.com/yandex-research/tabular-dl-revisiting-models/tree/main/package/README.md"
Documentation = "https://github.com/yandex-research/tabular-dl-revisiting-models/tree/main/package/README.md"

[tool.black]
skip_string_normalization = true

[tool.flit.module]
name = "rtdl_revisiting_models"

[tool.isort]
profile = "black"
multi_line_output = 3
known_first_party = ["rtdl_revisiting_models"]

[tool.mypy]
check_untyped_defs = true
ignore_missing_imports = true

[tool.ruff]
line-length = 88
extend-select = ["RUF", "UP", "E101", "E501"]
target-version = "py38"
